### PR TITLE
Mouse and touchscreen work with Chrome

### PR DESCRIPTION
**Pull request by mattallen37**

### CODE REVIEW

**Comment by CleoQc** [comment]
Could you put the URL of the page where the info was found?

**Comment by mattallen37** [comment]
The location of the bug and the idea of how to fix it was found [here](https://groups.google.com/forum/#!topic/novnc/bOpKeuZCd7s).

**Comment by CleoQc** [comment]
Tested locally on a non-touch screen, and everything still fine. YEAH!

**Comment by DexterInd** [comment]
Brilliant work!!!

**Pull request merged**
